package com.lucca.ko.data.backup

import com.lucca.ko.data.db.MealSlot
import com.lucca.ko.data.db.StockStatus
import kotlinx.serialization.Serializable

/*
 * A FROZEN, verbatim copy of the schema-1 backup format.
 *
 * The original mistake was serialising the Room entities directly: adding a column silently
 * changed the on-disk format, and making `MealPlanEntry.dishId` nullable would have made every
 * existing backup file unreadable. These classes exist so a v1 file can always be read, however
 * far the live entities drift.
 *
 * Do not edit this file. Ever. If the format needs to change, that is a new version.
 */

@Serializable
data class PantryItemV1(
    val id: Long = 0,
    val name: String,
    val normalizedName: String,
    val category: String = "Other",
    val status: StockStatus = StockStatus.IN_STOCK,
    val quantity: String? = null,
    val note: String? = null,
    val searchName: String? = null,
    val updatedAt: Long = 0,
)

@Serializable
data class DishV1(
    val id: Long = 0,
    val title: String,
    val sourceUrl: String? = null,
    val imageUrl: String? = null,
    val mealdbId: String? = null,
    val instructions: String? = null,
    val createdAt: Long = 0,
)

@Serializable
data class DishIngredientV1(
    val id: Long = 0,
    val dishId: Long,
    val rawName: String,
    val normalizedName: String,
    val measure: String? = null,
    val pantryItemId: Long? = null,
)

@Serializable
data class MealPlanEntryV1(
    val id: Long = 0,
    val date: String,
    val slot: MealSlot = MealSlot.DINNER,
    val dishId: Long,
)

@Serializable
data class ShoppingListItemV1(
    val id: Long = 0,
    val name: String,
    val normalizedName: String,
    val category: String = "Other",
    val pantryItemId: Long? = null,
    val checked: Boolean = false,
    val addedAt: Long = 0,
)

@Serializable
data class SettingsV1(
    val ollamaBaseUrl: String = "",
    val ollamaModel: String = "",
    val suggestionCount: Int = 5,
)

@Serializable
data class KoBackupV1(
    val schema: Int = 1,
    val app: String = "KO Kitchen",
    val exportedAt: Long = 0,
    val settings: SettingsV1 = SettingsV1(),
    val pantry: List<PantryItemV1> = emptyList(),
    val dishes: List<DishV1> = emptyList(),
    val dishIngredients: List<DishIngredientV1> = emptyList(),
    val mealPlan: List<MealPlanEntryV1> = emptyList(),
    val shopping: List<ShoppingListItemV1> = emptyList(),
)
